const { withPodfile } = require("@expo/config-plugins")
const { mergeContents } = require("@expo/config-plugins/build/utils/generateCode")

const TAG = "withIosModularHeaders"
const ANCHOR = /prepare_react_native_project!/
const FLAG = "use_modular_headers!"

/**
 * Injects `use_modular_headers!` into the generated ios/Podfile, just
 * after `prepare_react_native_project!` — the same anchor
 * `@react-native-firebase/app`'s own `withIosDisableSPM` plugin uses for
 * its `$RNFirebaseDisableSPM` flag, since both need to land before the
 * `target` block.
 *
 * Needed because CocoaPods refuses to link Firebase's Swift pods
 * (FirebaseCoreInternal, FirebaseCrashlytics, FirebaseSessions) as
 * static libraries without it: they depend on GoogleUtilities/nanopb/
 * GoogleDataTransport, which don't define Swift modules on their own —
 * `pod install` fails with "does not define modules" otherwise. This
 * has nothing to do with the earlier SPM-vs-static-linkage error
 * `disableSPM` fixes; it's the next thing CocoaPods requires once
 * Firebase resolves through CocoaPods instead of SPM.
 *
 * This has to be a local plugin, not a hand-edit to ios/Podfile
 * directly — that file is regenerated by every `expo prebuild`, per
 * CLAUDE.md's "never hand-edit ios/, edit app.json instead" rule.
 */
const withIosModularHeaders = (config) => {
  return withPodfile(config, (config) => {
    config.modResults.contents = mergeContents({
      src: config.modResults.contents,
      newSrc: FLAG,
      tag: TAG,
      anchor: ANCHOR,
      offset: 1,
      comment: "#",
    }).contents
    return config
  })
}

module.exports = withIosModularHeaders
